// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqcrocbegicttoypelge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xY3JvY2JlZ2ljdHRveXBlbGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzIxNDcsImV4cCI6MjA2NTE0ODE0N30.bWIMeJ5u0mrr2TEU86G8fN_nlAgwOKRLyKHYgTyCLP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);